export type SeedQuizQuestion = {
  question: string
  answer: string
  options: string[]
  explanation: string
  type?: 'multiple_choice' | 'true_false' | 'code_snippet'
}

const banks: Array<[string, SeedQuizQuestion]> = [
  ['Fundamentos cloud', { question: '¿Qué propiedad permite que un servicio cloud ajuste recursos según la demanda?', answer: 'Elasticidad', options: ['Elasticidad', 'Latencia fija', 'Cableado local'], explanation: 'La elasticidad permite aumentar o reducir recursos según la demanda.' }],
  ['Amazon EC2', { question: '¿Qué recurso define las reglas de tráfico de una instancia EC2?', answer: 'Security group', options: ['Security group', 'S3 bucket', 'CloudWatch alarm'], explanation: 'El security group controla el tráfico entrante y saliente de la instancia.' }],
  ['Amazon S3', { question: '¿Qué modelo de almacenamiento usa Amazon S3?', answer: 'Objetos', options: ['Objetos', 'Bloques locales', 'Cintas magnéticas'], explanation: 'S3 almacena datos como objetos dentro de buckets.' }],
  ['AWS IAM', { question: '¿Qué principio recomienda conceder solo los permisos necesarios?', answer: 'Mínimo privilegio', options: ['Mínimo privilegio', 'Acceso anónimo', 'Administrador permanente'], explanation: 'El mínimo privilegio reduce el impacto de credenciales o acciones comprometidas.' }],
  ['Amazon VPC', { question: '¿Qué componente permite enrutar tráfico entre subredes y otros destinos?', answer: 'Route table', options: ['Route table', 'IAM policy', 'S3 lifecycle'], explanation: 'La tabla de rutas determina los destinos del tráfico de una subred.' }],
  ['Amazon CloudWatch', { question: '¿Qué dato representa una medición numérica recogida por CloudWatch?', answer: 'Métrica', options: ['Métrica', 'Grupo IAM', 'Imagen AMI'], explanation: 'Las métricas son series temporales numéricas usadas para observar recursos y aplicaciones.' }],
  ['AWS CLI', { question: '¿Qué comando consulta información de una instancia EC2?', answer: 'aws ec2 describe-instances', options: ['aws ec2 describe-instances', 'aws s3 sync-only', 'aws iam run-server'], explanation: 'describe-instances devuelve la configuración y estado de instancias EC2.' , type: 'code_snippet'}],
  ['Terraform', { question: '¿Qué archivo suele declarar la configuración principal de Terraform?', answer: 'main.tf', options: ['main.tf', 'Dockerfile', 'package-lock.json'], explanation: 'Los archivos .tf contienen la configuración declarativa de Terraform.' }],
  ['Docker', { question: '¿Qué instrucción define la imagen base de un Dockerfile?', answer: 'FROM', options: ['FROM', 'PULLBASE', 'USEIMAGE'], explanation: 'FROM inicia un Dockerfile indicando la imagen base.' , type: 'code_snippet'}],
  ['GitHub Actions', { question: '¿Dónde se define normalmente un workflow de GitHub Actions?', answer: '.github/workflows', options: ['.github/workflows', '.git/hooks/remote', 'actions.config'], explanation: 'Los workflows se guardan como YAML dentro de .github/workflows.' }],
  ['Proyecto final', { question: '¿Qué evidencia demuestra mejor que un proyecto DevOps es reproducible?', answer: 'Código, automatización y documentación versionados', options: ['Código, automatización y documentación versionados', 'Una captura aislada', 'Una presentación sin repositorio'], explanation: 'La evidencia versionada permite revisar y repetir el despliegue.' }],
  ['Fundamentos de DevOps', { question: '¿Qué práctica acorta el ciclo entre cambios y feedback?', answer: 'Integración continua', options: ['Integración continua', 'Cambios manuales en producción', 'Copias sin versionar'], explanation: 'La integración continua valida cambios frecuentemente y entrega feedback rápido.' }],
  ['Linux y Bash', { question: '¿Qué comando muestra el directorio de trabajo actual?', answer: 'pwd', options: ['pwd', 'whereis-all', 'cd --show'], explanation: 'pwd imprime la ruta del directorio actual.', type: 'code_snippet' }],
  ['Git y control', { question: '¿Qué comando crea un commit con los cambios preparados?', answer: 'git commit', options: ['git commit', 'git branch --merge-only', 'git publish'], explanation: 'git commit registra en el historial los cambios del área de preparación.', type: 'code_snippet' }],
  ['Cloud básico', { question: '¿Qué ventaja caracteriza a la infraestructura cloud frente a comprar servidores?', answer: 'Pago según uso', options: ['Pago según uso', 'Capacidad fija obligatoria', 'Sin monitorización'], explanation: 'El cloud permite consumir capacidad y pagar según el uso o la reserva contratada.' }],
  ['Docker y contenedores', { question: '¿Qué aísla principalmente un contenedor?', answer: 'El proceso y sus dependencias', options: ['El proceso y sus dependencias', 'Un centro de datos completo', 'Solo el nombre del proyecto'], explanation: 'Un contenedor empaqueta un proceso con sus dependencias usando aislamiento del sistema operativo.' }],
  ['Terraform e Infraestructura', { question: '¿Qué comando muestra el cambio previsto antes de aplicar Terraform?', answer: 'terraform plan', options: ['terraform plan', 'terraform preview-only', 'terraform diff-state'], explanation: 'terraform plan calcula y muestra las acciones previstas.', type: 'code_snippet' }],
  ['Ansible y configuration', { question: '¿Qué formato usa habitualmente un playbook de Ansible?', answer: 'YAML', options: ['YAML', 'JPEG', 'SQL'], explanation: 'Los playbooks de Ansible se expresan habitualmente en YAML.' }],
  ['Kubernetes básico', { question: '¿Qué recurso mantiene el número deseado de réplicas de Pods?', answer: 'Deployment', options: ['Deployment', 'ConfigMap', 'Namespace'], explanation: 'Un Deployment gestiona réplicas y actualizaciones declarativas de Pods.' }],
  ['Helm y GitOps', { question: '¿Qué empaqueta Helm para instalar aplicaciones en Kubernetes?', answer: 'Charts', options: ['Charts', 'Buckets', 'Snapshots'], explanation: 'Un chart es el paquete versionado de plantillas y valores de una aplicación Kubernetes.' }],
  ['Monitoring y logging', { question: '¿Qué diferencia básica hay entre logs y métricas?', answer: 'Los logs son eventos y las métricas valores medibles', options: ['Los logs son eventos y las métricas valores medibles', 'Son exactamente lo mismo', 'Las métricas solo contienen texto libre'], explanation: 'Los logs describen eventos; las métricas permiten analizar valores y tendencias.' }],
  ['Pipeline de CI/CD', { question: '¿Qué etapa debe ejecutarse antes de desplegar automáticamente?', answer: 'Pruebas automatizadas', options: ['Pruebas automatizadas', 'Borrar el repositorio', 'Desactivar los controles'], explanation: 'Las pruebas automatizadas reducen el riesgo de desplegar cambios defectuosos.' }],
  ['Seguridad y hardening', { question: '¿Qué medida reduce la exposición de un servicio innecesario?', answer: 'Deshabilitarlo o restringirlo', options: ['Deshabilitarlo o restringirlo', 'Publicarlo sin autenticación', 'Compartir sus credenciales'], explanation: 'Reducir servicios y puertos expuestos forma parte del hardening.' }],
  ['Fundamentos de IA', { question: '¿Qué representa un token para un modelo de lenguaje?', answer: 'Una unidad de texto procesada por el modelo', options: ['Una unidad de texto procesada por el modelo', 'Un servidor físico', 'Una regla de firewall'], explanation: 'Los modelos procesan el texto dividido en tokens.' }],
  ['Python aplicado', { question: '¿Qué estructura de Python conserva pares clave-valor?', answer: 'dict', options: ['dict', 'tuple-only', 'modulepath'], explanation: 'dict representa un mapeo entre claves y valores.', type: 'code_snippet' }],
  ['Prompt engineering', { question: '¿Qué mejora la consistencia de una respuesta de un modelo?', answer: 'Definir instrucciones, contexto y formato esperado', options: ['Definir instrucciones, contexto y formato esperado', 'Eliminar el contexto', 'Usar instrucciones contradictorias'], explanation: 'Un prompt claro acota la tarea y el formato de salida.' }],
  ['RAG para', { question: '¿Qué aporta la recuperación en un sistema RAG?', answer: 'Contexto relevante para generar la respuesta', options: ['Contexto relevante para generar la respuesta', 'Un firewall de red', 'Un reemplazo del modelo'], explanation: 'RAG recupera información relevante que el modelo puede usar como contexto.' }],
  ['Agentes de IA', { question: '¿Qué permite a un agente completar tareas operativas?', answer: 'Usar herramientas con límites definidos', options: ['Usar herramientas con límites definidos', 'Ejecutar todo sin permisos', 'Ignorar resultados'], explanation: 'Las herramientas permiten actuar, pero deben estar acotadas y auditadas.' }],
  ['Plataformas cloud de IA', { question: '¿Qué decisión debe evaluarse al elegir una plataforma de IA?', answer: 'Modelo, seguridad, coste y operación', options: ['Modelo, seguridad, coste y operación', 'Solo el color de la consola', 'Solo el nombre del proveedor'], explanation: 'La elección debe considerar requisitos técnicos, de seguridad y operativos.' }],
  ['MLOps y LLMOps', { question: '¿Qué práctica detecta degradación del modelo en producción?', answer: 'Monitorizar calidad y deriva', options: ['Monitorizar calidad y deriva', 'Eliminar métricas', 'Cambiar el modelo sin registro'], explanation: 'La monitorización de calidad y deriva permite detectar cambios en los datos o resultados.' }],
  ['Kubernetes/OpenShift para IA', { question: '¿Qué objetivo tiene escalar el serving de un modelo?', answer: 'Atender la demanda manteniendo latencia y disponibilidad', options: ['Atender la demanda manteniendo latencia y disponibilidad', 'Eliminar los endpoints', 'Desactivar el balanceo'], explanation: 'El serving debe responder a la demanda con objetivos operativos medibles.' }],
  ['Observabilidad, evaluación', { question: '¿Qué debe incluir una evaluación útil de una aplicación de IA?', answer: 'Calidad, latencia, coste y seguridad', options: ['Calidad, latencia, coste y seguridad', 'Solo el número de líneas', 'Solo el color de la interfaz'], explanation: 'La evaluación combina calidad del resultado y características operativas.' }],
  ['Seguridad, privacidad', { question: '¿Qué principio limita el uso de datos personales en una aplicación de IA?', answer: 'Minimización de datos', options: ['Minimización de datos', 'Retención indefinida', 'Acceso público'], explanation: 'La minimización limita los datos a los necesarios para el propósito declarado.' }],
  ['Proyecto final y posicionamiento', { question: '¿Qué hace creíble un proyecto de IA para DevOps?', answer: 'Repositorio reproducible con resultados medidos', options: ['Repositorio reproducible con resultados medidos', 'Una afirmación sin evidencia', 'Un título sin implementación'], explanation: 'La implementación reproducible y las métricas permiten evaluar el proyecto.' }]
]

export function getSeedQuizForModule(title: string): SeedQuizQuestion[] {
  const match = banks.find(([prefix]) => title.includes(prefix))
  return match ? [match[1]] : []
}
